from server.config import Config
from flask import Flask
from peewee import *
from playhouse.flask_utils import FlaskDB


# Init app
app = Flask(__name__)
# Default to production environment for security
app.config.from_object(Config)
# Init db
db_wrapper = FlaskDB(app)
db = db_wrapper.database

# This hook ensures that a connection is opened to handle any queries
# generated by the request.
@app.before_request
def _db_connect():
    if db.is_closed():
        db.connect()


# This hook ensures that the connection is closed when we've finished
# processing the request.
@app.teardown_request
def _db_close(exc):
    if not db.is_closed():
        db.close()


from server import routes, models
