"""empty message

Revision ID: 21e0f01c94dd
Revises: 3e39c10679f5
Create Date: 2018-11-21 16:41:16.160051

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21e0f01c94dd'
down_revision = '3e39c10679f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('snippets', sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('snippets', sa.Column('title', sa.String(length=125), nullable=True))
    op.add_column('snippets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'snippets', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('first_name', sa.String(length=32), nullable=False))
    op.add_column('users', sa.Column('last_name', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_constraint(None, 'snippets', type_='foreignkey')
    op.drop_column('snippets', 'user_id')
    op.drop_column('snippets', 'title')
    op.drop_column('snippets', 'keywords')
    # ### end Alembic commands ###
